<?php defined('AUTOSAV_ROOT') or die; $e = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); ?>
<div class="container-fluid py-3">
  <div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $e($file['fic_nom_original'] ?? '') ?></h1><div><a class="btn btn-outline-secondary" href="/files">Retour</a> <a class="btn btn-primary" href="/files/<?= (int)$file['fic_id'] ?>/download">Télécharger</a></div></div>
  <div class="row"><div class="col-md-6"><div class="card"><div class="card-header">Métadonnées</div><div class="card-body">
    <dl class="row"><dt class="col-sm-4">UUID</dt><dd class="col-sm-8"><code><?= $e($file['fic_uuid'] ?? '') ?></code></dd><dt class="col-sm-4">MIME</dt><dd class="col-sm-8"><?= $e($file['fic_mime_type'] ?? '') ?></dd><dt class="col-sm-4">Taille</dt><dd class="col-sm-8"><?= number_format(((int)($file['fic_taille_octets'] ?? 0))/1024, 1, ',', ' ') ?> Ko</dd><dt class="col-sm-4">Checksum</dt><dd class="col-sm-8"><code><?= $e($file['fic_checksum_sha256'] ?? '') ?></code></dd><dt class="col-sm-4">Chiffré</dt><dd class="col-sm-8"><?= !empty($file['fic_est_chiffre']) ? 'Oui' : 'Non' ?></dd><dt class="col-sm-4">Créé</dt><dd class="col-sm-8"><?= $e($file['fic_cree_le'] ?? '') ?></dd></dl>
    <form method="post" action="/files/<?= (int)$file['fic_id'] ?>/delete" data-confirm="Supprimer logiquement ce fichier ?"><input type="hidden" name="_csrf_token" value="<?= $e($csrf_token ?? '') ?>"><button class="btn btn-outline-danger">Supprimer logiquement</button></form>
  </div></div></div>
  <div class="col-md-6"><div class="card mb-3"><div class="card-header">Liaisons</div><div class="card-body p-0"><table class="table table-sm mb-0"><thead><tr><th>Cible</th><th>ID</th><th>Type</th><th>Créée</th></tr></thead><tbody><?php foreach (($links ?? []) as $link): ?><tr><td><?= $e($link['lfi_cible_type'] ?? '') ?></td><td><?= (int)($link['lfi_cible_id'] ?? 0) ?></td><td><?= $e($link['lfi_type_liaison'] ?? '') ?></td><td><?= $e($link['lfi_cree_le'] ?? '') ?></td></tr><?php endforeach; ?><?php if (empty($links)): ?><tr><td colspan="4" class="text-muted text-center">Aucune liaison.</td></tr><?php endif; ?></tbody></table></div></div>
  <div class="card"><div class="card-header">Ajouter une liaison</div><div class="card-body"><form method="post" action="/files/<?= (int)$file['fic_id'] ?>/link"><input type="hidden" name="_csrf_token" value="<?= $e($csrf_token ?? '') ?>"><div class="row"><div class="col-md-4"><input class="form-control" name="lfi_cible_type" placeholder="Type cible" required></div><div class="col-md-3"><input class="form-control" type="number" name="lfi_cible_id" placeholder="ID" required></div><div class="col-md-3"><input class="form-control" name="lfi_type_liaison" value="piece_jointe"></div><div class="col-md-2"><button class="btn btn-primary btn-block">Lier</button></div></div></form></div></div></div></div>
</div>
