<?php defined('AUTOSAV_ROOT') or die; $e = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); ?>
<div class="container-fluid py-3">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <div><h1 class="h3 mb-0">Documents juridiques</h1><p class="text-muted mb-0">Documents versionnés, liés aux sociétés et acceptés par les utilisateurs.</p></div>
    <a class="btn btn-primary" href="/legal-documents/create">Nouveau document</a>
  </div>
  <div class="row mb-3"><div class="col-md-3"><div class="small-box bg-light"><div class="inner"><h3><?= (int)($stats['total'] ?? 0) ?></h3><p>Documents</p></div></div></div><div class="col-md-3"><div class="small-box bg-light"><div class="inner"><h3><?= (int)($stats['types'] ?? 0) ?></h3><p>Types</p></div></div></div><div class="col-md-3"><div class="small-box bg-light"><div class="inner"><h3><?= (int)($stats['expires'] ?? 0) ?></h3><p>Expirés</p></div></div></div><div class="col-md-3"><div class="small-box bg-light"><div class="inner"><h3><?= (int)($stats['archives'] ?? 0) ?></h3><p>Archivés</p></div></div></div></div>
  <div class="card mb-3"><div class="card-body"><form method="get" action="/legal-documents" class="row g-2"><div class="col-md-4"><label>Recherche</label><input class="form-control" name="q" value="<?= $e($filters['q'] ?? '') ?>"></div><div class="col-md-3"><label>Type</label><select class="form-control" name="type"><option value="">Tous</option><?php foreach (($types ?? []) as $type): $t=(string)$type['type']; ?><option value="<?= $e($t) ?>" <?= (($filters['type'] ?? '')===$t)?'selected':'' ?>><?= $e($t) ?> (<?= (int)$type['total'] ?>)</option><?php endforeach; ?></select></div><div class="col-md-3"><label>Société</label><select class="form-control" name="company_id"><option value="0">Toutes</option><?php foreach (($societes ?? []) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= ((int)($filters['company_id'] ?? 0)===(int)$s['soc_id'])?'selected':'' ?>><?= $e($s['soc_nom']) ?></option><?php endforeach; ?></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary btn-block">Filtrer</button></div></form></div></div>
  <div class="card"><div class="card-body p-0 table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Type</th><th>Titre</th><th>Version</th><th>Société</th><th>Validité</th><th>Liens</th><th>Acceptations</th><th class="text-right">Actions</th></tr></thead><tbody><?php foreach (($documents ?? []) as $d): ?><tr><td><span class="badge badge-light"><?= $e($d['dju_type_document'] ?? '') ?></span></td><td><a href="/legal-documents/<?= (int)$d['dju_id'] ?>"><?= $e($d['dju_titre'] ?? '') ?></a></td><td><?= $e($d['dju_version'] ?? '') ?></td><td><?= $e($d['societe_nom'] ?? 'Global') ?></td><td><?= $e($d['dju_valide_du'] ?? '-') ?> → <?= $e($d['dju_valide_au'] ?? '-') ?></td><td><?= (int)($d['societes_liees'] ?? 0) ?></td><td><?= (int)($d['acceptations_total'] ?? 0) ?></td><td class="text-right"><a class="btn btn-sm btn-outline-primary" href="/legal-documents/<?= (int)$d['dju_id'] ?>">Voir</a></td></tr><?php endforeach; ?><?php if (empty($documents)): ?><tr><td colspan="8" class="text-center text-muted py-4">Aucun document.</td></tr><?php endif; ?></tbody></table></div></div>
</div>
