<?php declare(strict_types=1);
$h = static fn(mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$role = $role ?? [];
$errors = $errors ?? [];
$publicationScopes = $publicationScopes ?? ['interne' => 'Interne société'];
$isEdit = !empty($role['rol_id']);
$isSuperAdmin = !empty($isSuperAdmin);
$value = static function (string $key, mixed $default = '') use ($role): mixed { return $role[$key] ?? $default; };
$currentScope = (string) ($role['rol_portee_code'] ?? $role['rol_scope'] ?? 'interne');
if (!isset($publicationScopes[$currentScope])) { $currentScope = array_key_first($publicationScopes) ?: 'interne'; }
?>
<section class="content-header"><div class="container-fluid d-flex justify-content-between align-items-center"><h1><i class="fas fa-user-shield mr-2"></i><?= $h($page_title ?? 'Rôle') ?></h1><a href="/roles" class="btn btn-light btn-sm">Retour</a></div></section>
<section class="content"><div class="container-fluid">
  <?php if ($errors): ?><div class="alert alert-danger"><ul class="mb-0"><?php foreach ($errors as $error): ?><li><?= $h($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
  <form method="post" action="<?= $h($action ?? '/roles/store') ?>">
    <input type="hidden" name="_csrf_token" value="<?= $h($csrf_token ?? '') ?>">
    <div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Définition du rôle</h3></div><div class="card-body">
      <div class="row"><div class="form-group col-md-4"><label>Code <span class="text-danger">*</span></label><input name="rol_code" class="form-control" required value="<?= $h($value('rol_code')) ?>" placeholder="ex: chef_atelier"></div><div class="form-group col-md-8"><label>Nom <span class="text-danger">*</span></label><input name="rol_nom" class="form-control" required value="<?= $h($value('rol_nom')) ?>"></div></div>
      <div class="row"><div class="form-group col-md-4"><label>Module</label><select name="rol_module_id" class="form-control"><option value="">Noyau / aucun module spécifique</option><?php foreach (($modules ?? []) as $m): ?><option value="<?= (int)$m['mod_id'] ?>" <?= ((string)$value('rol_module_id') === (string)$m['mod_id']) ? 'selected' : '' ?>><?= $h($m['mod_nom']) ?></option><?php endforeach; ?></select></div><div class="form-group col-md-4"><label>Portée de publication</label><select name="rol_portee_code" class="form-control"><?php foreach ($publicationScopes as $code => $label): ?><option value="<?= $h($code) ?>" <?= $currentScope === (string) $code ? 'selected' : '' ?>><?= $h($label) ?></option><?php endforeach; ?></select><small class="form-text text-muted">Plateforme : super-admin. Réseau : constructeur/marque/importateur selon rattachements. Interne : société active.</small></div><div class="form-group col-md-4"><label>Société propriétaire</label><select name="rol_societe_proprietaire_id" class="form-control" <?= $isSuperAdmin ? '' : 'disabled' ?>><option value=""><?= $isSuperAdmin ? 'Plateforme / global' : 'Société active' ?></option><?php foreach (($societes ?? []) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= ((string)$value('rol_societe_proprietaire_id') === (string)$s['soc_id']) ? 'selected' : '' ?>><?= $h($s['soc_nom']) ?></option><?php endforeach; ?></select><?php if (!$isSuperAdmin): ?><input type="hidden" name="rol_societe_proprietaire_id" value="<?= (int)($activeCompanyId ?? 0) ?>"><?php endif; ?></div></div>
      <div class="row"><div class="form-group col-md-6"><label>Type de société</label><select name="rol_type_societe_id" class="form-control"><option value="">— Aucun type spécifique —</option><?php foreach (($typesSocietes ?? []) as $t): ?><option value="<?= (int)$t['tso_id'] ?>" <?= ((string)$value('rol_type_societe_id') === (string)$t['tso_id']) ? 'selected' : '' ?>><?= $h($t['tso_nom']) ?></option><?php endforeach; ?></select><small class="form-text text-muted"><?= empty($typesSocietes) ? 'Aucun type de société disponible pour votre périmètre.' : 'Restreint aux types de votre société active.' ?></small></div><div class="form-group col-md-6"><label>Statut</label><select name="rol_statut_id" class="form-control"><?php foreach (($statuts ?? []) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= ((string)$value('rol_statut_id', 1) === (string)$st['sta_id']) ? 'selected' : '' ?>><?= $h($st['sta_libelle']) ?></option><?php endforeach; ?></select></div></div>
      <div class="form-group"><label>Description</label><textarea name="rol_description" class="form-control" rows="3"><?= $h($value('rol_description')) ?></textarea></div>
    </div><div class="card-footer text-right"><button class="btn btn-primary" type="submit">Enregistrer</button></div></div>
  </form>
  <?php if ($isEdit): ?><form method="post" action="/roles/<?= (int)$role['rol_id'] ?>/permissions/sync"><input type="hidden" name="_csrf_token" value="<?= $h($csrf_token ?? '') ?>"><div class="card card-outline card-secondary"><div class="card-header"><h3 class="card-title">Permissions explicites du rôle</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm table-hover mb-0"><thead class="thead-light"><tr><th>Permission</th><th>Module</th><th>Description</th><th style="width:220px">Effet</th></tr></thead><tbody><?php foreach (($permissions ?? []) as $permission): ?><?php $effet = (string)($permission['rpe_effet'] ?? ''); ?><tr><td><code><?= $h($permission['per_code'] ?? '') ?></code></td><td><?= $h($permission['mod_nom'] ?? 'Noyau') ?></td><td><?= $h($permission['per_description'] ?? '') ?></td><td><select name="permissions[<?= (int)$permission['per_id'] ?>]" class="form-control form-control-sm"><option value="" <?= $effet === '' ? 'selected' : '' ?>>Non défini</option><option value="autoriser" <?= $effet === 'autoriser' ? 'selected' : '' ?>>Autoriser</option><option value="refuser" <?= $effet === 'refuser' ? 'selected' : '' ?>>Refuser</option></select></td></tr><?php endforeach; ?></tbody></table></div><div class="card-footer d-flex justify-content-between align-items-center"><span class="text-muted">En cas de conflit, la règle applicative est : <strong>refuser &gt; autoriser</strong>.</span><button class="btn btn-primary" type="submit">Synchroniser les permissions</button></div></div></form><?php endif; ?>
</div></section>
