<?php declare(strict_types=1);
$h = static fn(mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$filters = $filters ?? [];
$isSuperAdmin = !empty($isSuperAdmin);
$activeCompanyId = (int) ($activeCompanyId ?? 0);
$scopeBadge = static function (string $scope): string { return match ($scope) { 'plateforme' => '<span class="badge badge-dark">Plateforme</span>', 'reseau' => '<span class="badge badge-info">Réseau</span>', default => '<span class="badge badge-secondary">Interne</span>' }; };
?>
<section class="content-header"><div class="container-fluid d-flex justify-content-between align-items-center"><h1><i class="fas fa-user-shield mr-2"></i>Rôles &amp; permissions</h1><div><a href="/permissions" class="btn btn-outline-secondary btn-sm"><i class="fas fa-key mr-1"></i>Permissions</a><a href="/access-policies" class="btn btn-outline-secondary btn-sm"><i class="fas fa-project-diagram mr-1"></i>ABAC</a><a href="/roles/create" class="btn btn-primary btn-sm"><i class="fas fa-plus mr-1"></i>Nouveau rôle</a></div></div></section>
<section class="content"><div class="container-fluid"><div class="alert alert-light border small">Gestion réservée aux profils <strong>PDG</strong> et <strong>chef de service</strong>. Les rôles réseau hérités sont visibles, mais seul le propriétaire peut les modifier.</div><div class="card card-outline card-primary"><div class="card-header"><form method="get" class="form-inline"><input type="search" name="q" value="<?= $h($filters['q'] ?? '') ?>" class="form-control form-control-sm mr-2" placeholder="Code, nom, description"><select name="module_id" class="form-control form-control-sm mr-2"><option value="">Tous les modules</option><?php foreach (($modules ?? []) as $m): ?><option value="<?= (int) $m['mod_id'] ?>" <?= ((string)($filters['module_id'] ?? '') === (string)$m['mod_id']) ? 'selected' : '' ?>><?= $h($m['mod_nom']) ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-primary" type="submit">Filtrer</button></form></div><div class="card-body p-0 table-responsive"><table class="table table-striped table-hover mb-0"><thead class="thead-light"><tr><th>Code</th><th>Nom</th><th>Module</th><th>Portée</th><th>Société propriétaire</th><th>Utilisateurs</th><th>Permissions</th><th>Statut</th><th class="text-right">Actions</th></tr></thead><tbody><?php if (empty($roles)): ?><tr><td colspan="9" class="text-center text-muted py-4">Aucun rôle trouvé.</td></tr><?php endif; ?><?php foreach (($roles ?? []) as $role): ?><?php $ownerId = (int)($role['rol_societe_proprietaire_id'] ?? 0); $scope = (string)($role['rol_portee_code'] ?? $role['rol_scope'] ?? ($ownerId > 0 ? 'interne' : 'plateforme')); $canEdit = $isSuperAdmin || ($ownerId > 0 && $ownerId === $activeCompanyId); ?><tr><td><code><?= $h($role['rol_code'] ?? '') ?></code></td><td><?= $h($role['rol_nom'] ?? '') ?></td><td><?= $h($role['mod_nom'] ?? 'Noyau / global') ?></td><td><?= $scopeBadge($scope) ?></td><td><?= $h($role['societe_proprietaire_nom'] ?? 'Global') ?></td><td><span class="badge badge-info"><?= (int)($role['utilisateurs_count'] ?? 0) ?></span></td><td><span class="badge badge-success">+<?= (int)($role['permissions_autorisees_count'] ?? 0) ?></span> <span class="badge badge-danger">-<?= (int)($role['permissions_refusees_count'] ?? 0) ?></span></td><td><?= $h($role['statut_libelle'] ?? $role['statut_code'] ?? '—') ?></td><td class="text-right text-nowrap"><a class="btn btn-xs btn-outline-secondary" href="/roles/<?= (int)$role['rol_id'] ?>">Voir</a><?php if ($canEdit): ?> <a class="btn btn-xs btn-outline-primary" href="/roles/<?= (int)$role['rol_id'] ?>/edit">Modifier</a><?php else: ?> <span class="text-muted small">Lecture</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></section>
