server {
    listen 443 ssl http2;
    server_name autosav.example.tld;
    root /var/www/autosav/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/autosav.example.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/autosav.example.tld/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location ~* /(storage|database|config|Core|Modules|vendor)/ {
        deny all;
    }
}
