<?php defined('AUTOSAV_ROOT') or die; $h=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); $a=$abonnement??null; $refs=$refs??[]; $isEdit=!empty($a['abo_id']); $action=$isEdit?'/abonnements/'.(int)$a['abo_id'].'/update':'/abonnements/store'; ?>
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $isEdit?'Modifier l’abonnement':'Créer un abonnement' ?></h1><a class="btn btn-outline-secondary" href="<?= url('/abonnements') ?>">Retour</a></div>
<form method="post" action="<?= url($action) ?>" class="card card-body"><?= csrf_field() ?><div class="row g-3">
  <div class="col-md-6"><label class="form-label">Société *</label><select class="form-select" name="abo_societe_id" required><option value="">Sélectionner</option><?php foreach(($refs['societes']??[]) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= (int)($a['abo_societe_id']??0)===(int)$s['soc_id']?'selected':'' ?>><?= $h($s['soc_nom']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-6"><label class="form-label">Formule</label><select class="form-select" name="abo_formule_abonnement_id"><option value="">Aucune</option><?php foreach(($refs['formules']??[]) as $f): ?><option value="<?= (int)$f['fab_id'] ?>" <?= (int)($a['abo_formule_abonnement_id']??0)===(int)$f['fab_id']?'selected':'' ?>><?= $h($f['fab_nom']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Statut abonnement</label><select class="form-select" name="abo_statut_abonnement_id"><option value="">Aucun</option><?php foreach(($refs['statuts']??[]) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= (int)($a['abo_statut_abonnement_id']??0)===(int)$st['sta_id']?'selected':'' ?>><?= $h(($st['sta_domaine']??'').' — '.($st['sta_libelle']??'')) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Statut paiement</label><select class="form-select" name="abo_statut_paiement_id"><option value="">Aucun</option><?php foreach(($refs['statuts']??[]) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= (int)($a['abo_statut_paiement_id']??0)===(int)$st['sta_id']?'selected':'' ?>><?= $h(($st['sta_domaine']??'').' — '.($st['sta_libelle']??'')) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Début</label><input type="date" class="form-control" name="abo_debute_le" value="<?= $h(substr((string)($a['abo_debute_le']??''),0,10)) ?>"></div>
  <div class="col-md-3"><label class="form-label">Fin</label><input type="date" class="form-control" name="abo_termine_le" value="<?= $h(substr((string)($a['abo_termine_le']??''),0,10)) ?>"></div>
</div><div class="mt-4 d-flex gap-2"><button class="btn btn-primary">Enregistrer</button><?php if($isEdit): ?><button class="btn btn-outline-danger" formaction="<?= url('/abonnements/'.(int)$a['abo_id'].'/delete') ?>" formmethod="post" data-confirm="Supprimer cet abonnement ?">Supprimer</button><?php endif; ?></div></form></div>
