<?php defined('AUTOSAV_ROOT') or die; $h=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); $e=$espace??null; $refs=$refs??[]; $isEdit=!empty($e['eap_id']); $action=$isEdit?'/abonnements/espaces/'.(int)$e['eap_id'].'/update':'/abonnements/espaces/store'; ?>
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $isEdit?'Modifier l’espace applicatif':'Créer un espace applicatif' ?></h1><a class="btn btn-outline-secondary" href="<?= url('/abonnements/espaces') ?>">Retour</a></div>
<form method="post" action="<?= url($action) ?>" class="card card-body"><?= csrf_field() ?><div class="row g-3">
  <div class="col-md-6"><label class="form-label">Société *</label><select class="form-select" name="eap_societe_id" required><option value="">Sélectionner</option><?php foreach(($refs['societes']??[]) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= (int)($e['eap_societe_id']??0)===(int)$s['soc_id']?'selected':'' ?>><?= $h($s['soc_nom']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-6"><label class="form-label">Abonnement lié</label><select class="form-select" name="eap_abonnement_societe_id"><option value="">Aucun</option><?php foreach(($refs['abonnements']??[]) as $a): ?><option value="<?= (int)$a['abo_id'] ?>" <?= (int)($e['eap_abonnement_societe_id']??0)===(int)$a['abo_id']?'selected':'' ?>><?= $h(($a['soc_nom']??'').' — '.($a['fab_nom']??'sans formule')) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-4"><label class="form-label">Statut</label><select class="form-select" name="eap_statut_id"><option value="">Aucun</option><?php foreach(($refs['statuts']??[]) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= (int)($e['eap_statut_id']??0)===(int)$st['sta_id']?'selected':'' ?>><?= $h(($st['sta_domaine']??'').' — '.($st['sta_libelle']??'')) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"><label class="form-label">Blocage</label><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="eap_est_bloque" value="1" <?= !empty($e['eap_bloque_le'])?'checked':'' ?>><label class="form-check-label">Bloqué</label></div></div>
  <div class="col-md-6"><label class="form-label">Motif blocage</label><input class="form-control" name="eap_motif_blocage" value="<?= $h($e['eap_motif_blocage']??'') ?>"></div>
</div><div class="mt-4 d-flex gap-2"><button class="btn btn-primary">Enregistrer</button><?php if($isEdit): ?><button class="btn btn-outline-danger" formaction="<?= url('/abonnements/espaces/'.(int)$e['eap_id'].'/delete') ?>" formmethod="post" data-confirm="Supprimer cet espace ?">Supprimer</button><?php endif; ?></div></form></div>
