<?php defined('AUTOSAV_ROOT') or die; $h=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); $f=$formule??null; $refs=$refs??[]; $isEdit=!empty($f['fab_id']); $action=$isEdit?'/abonnements/formules/'.(int)$f['fab_id'].'/update':'/abonnements/formules/store'; ?>
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $isEdit?'Modifier la formule':'Créer une formule' ?></h1><a class="btn btn-outline-secondary" href="<?= url('/abonnements/formules') ?>">Retour</a></div>
<form method="post" action="<?= url($action) ?>" class="card card-body"><?= csrf_field() ?><div class="row g-3">
  <div class="col-md-3"><label class="form-label">Code *</label><input class="form-control" name="fab_code" required value="<?= $h($f['fab_code']??'') ?>" placeholder="premium, systeme..."></div>
  <div class="col-md-5"><label class="form-label">Nom *</label><input class="form-control" name="fab_nom" required value="<?= $h($f['fab_nom']??'') ?>"></div>
  <div class="col-md-2"><label class="form-label">Mode tarif</label><input class="form-control" name="fab_mode_tarif" value="<?= $h($f['fab_mode_tarif']??'personnalise') ?>"></div>
  <div class="col-md-2"><label class="form-label">Statut</label><select class="form-select" name="fab_statut_id"><option value="">Aucun</option><?php foreach(($refs['statuts']??[]) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= (int)($f['fab_statut_id']??0)===(int)$st['sta_id']?'selected':'' ?>><?= $h(($st['sta_domaine']??'').' — '.($st['sta_libelle']??'')) ?></option><?php endforeach; ?></select></div>
  <div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="fab_description" rows="3"><?= $h($f['fab_description']??'') ?></textarea></div>
  <div class="col-12"><label class="form-label">Fonctions / modules inclus au format JSON</label><textarea class="form-control font-monospace" name="fab_fonctions_json" rows="7" placeholder='{"modules":["noyau"],"limites":{}}'><?= $h($f['fab_fonctions_json']??'') ?></textarea><div class="form-text">Ce champ reste libre pour les futures règles tarifaires et limites d’usage.</div></div>
</div><div class="mt-4 d-flex gap-2"><button class="btn btn-primary">Enregistrer</button><?php if($isEdit): ?><button class="btn btn-outline-danger" formaction="<?= url('/abonnements/formules/'.(int)$f['fab_id'].'/delete') ?>" formmethod="post" data-confirm="Supprimer cette formule ?">Supprimer</button><?php endif; ?></div></form></div>
