<?php defined('AUTOSAV_ROOT') or die; $h=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); $formules=$formules??[]; $filters=$filters??[]; ?>
<div class="container-fluid py-3">
  <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-0">Formules d’abonnement</h1><p class="text-muted mb-0">Formules personnalisables par client, liées aux abonnements et aux modules activés.</p></div><div class="btn-group"><a class="btn btn-primary" href="<?= url('/abonnements/formules/create') ?>">Nouvelle formule</a><a class="btn btn-outline-secondary" href="<?= url('/abonnements') ?>">Abonnements</a></div></div>
  <form method="get" class="card card-body mb-3"><div class="row g-2"><div class="col-md-10"><input class="form-control" name="q" value="<?= $h($filters['q']??'') ?>" placeholder="Recherche code, nom, description"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filtrer</button></div></div></form>
  <div class="card"><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th>Code</th><th>Nom</th><th>Mode tarif</th><th>Statut</th><th>Abonnements</th><th>Modules sociétés</th><th></th></tr></thead><tbody>
    <?php foreach($formules as $f): ?><tr><td><code><?= $h($f['fab_code']) ?></code></td><td><?= $h($f['fab_nom']) ?></td><td><?= $h($f['fab_mode_tarif']) ?></td><td><?= $h($f['statut_libelle']??'—') ?></td><td><?= (int)($f['abonnements_total']??0) ?></td><td><?= (int)($f['modules_societes_total']??0) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="<?= url('/abonnements/formules/'.(int)$f['fab_id'].'/edit') ?>">Modifier</a></td></tr><?php endforeach; ?>
    <?php if(!$formules): ?><tr><td colspan="7" class="text-center text-muted py-4">Aucune formule.</td></tr><?php endif; ?>
  </tbody></table></div></div>
</div>
