<?php defined('AUTOSAV_ROOT') or die; $h=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); $m=$moduleSociete??null; $refs=$refs??[]; $isEdit=!empty($m['mos_id']); $action=$isEdit?'/abonnements/modules-societes/'.(int)$m['mos_id'].'/update':'/abonnements/modules-societes/store'; ?>
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $isEdit?'Modifier le module société':'Activer un module pour une société' ?></h1><a class="btn btn-outline-secondary" href="<?= url('/abonnements/modules-societes') ?>">Retour</a></div>
<form method="post" action="<?= url($action) ?>" class="card card-body"><?= csrf_field() ?><div class="row g-3">
  <div class="col-md-6"><label class="form-label">Société *</label><select class="form-select" name="mos_societe_id" required><option value="">Sélectionner</option><?php foreach(($refs['societes']??[]) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= (int)($m['mos_societe_id']??0)===(int)$s['soc_id']?'selected':'' ?>><?= $h($s['soc_nom']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-6"><label class="form-label">Module *</label><select class="form-select" name="mos_module_id" required><option value="">Sélectionner</option><?php foreach(($refs['modules']??[]) as $mod): ?><option value="<?= (int)$mod['mod_id'] ?>" <?= (int)($m['mos_module_id']??0)===(int)$mod['mod_id']?'selected':'' ?>><?= $h(($mod['mod_code']??'').' — '.($mod['mod_nom']??'')) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-4"><label class="form-label">Formule</label><select class="form-select" name="mos_formule_abonnement_id"><option value="">Aucune</option><?php foreach(($refs['formules']??[]) as $f): ?><option value="<?= (int)$f['fab_id'] ?>" <?= (int)($m['mos_formule_abonnement_id']??0)===(int)$f['fab_id']?'selected':'' ?>><?= $h($f['fab_nom']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Début</label><input type="datetime-local" class="form-control" name="mos_debute_le" value="<?= $h(str_replace(' ', 'T', substr((string)($m['mos_debute_le']??''),0,16))) ?>"></div>
  <div class="col-md-3"><label class="form-label">Fin</label><input type="datetime-local" class="form-control" name="mos_termine_le" value="<?= $h(str_replace(' ', 'T', substr((string)($m['mos_termine_le']??''),0,16))) ?>"></div>
  <div class="col-md-2"><label class="form-label">Statut</label><select class="form-select" name="mos_statut_id"><option value="">Aucun</option><?php foreach(($refs['statuts']??[]) as $st): ?><option value="<?= (int)$st['sta_id'] ?>" <?= (int)($m['mos_statut_id']??0)===(int)$st['sta_id']?'selected':'' ?>><?= $h($st['sta_libelle']??'') ?></option><?php endforeach; ?></select></div>
</div><div class="mt-4 d-flex gap-2"><button class="btn btn-primary">Enregistrer</button><?php if($isEdit): ?><button class="btn btn-outline-danger" formaction="<?= url('/abonnements/modules-societes/'.(int)$m['mos_id'].'/delete') ?>" formmethod="post" data-confirm="Supprimer cette activation ?">Supprimer</button><?php endif; ?></div></form></div>
