<?php
$h = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$contextes = $contextes ?? [];
$refs = $refs ?? [];
$filters = $filters ?? [];
?>
<div class="container-fluid py-3">
  <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Historique des contextes utilisateur</h1><p class="text-muted mb-0">Trace des changements de société, concession, marque, service et équipe.</p></div><a class="btn btn-outline-secondary" href="<?= url('/verrous') ?>">Verrous</a></div>
  <form method="get" class="card card-body mb-3"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Utilisateur</label><select class="form-select" name="utilisateur_id"><option value="0">Tous</option><?php foreach (($refs['utilisateurs'] ?? []) as $u): ?><option value="<?= (int)$u['uti_id'] ?>" <?= (int)($filters['utilisateur_id'] ?? 0)===(int)$u['uti_id']?'selected':'' ?>><?= $h(trim(($u['pui_prenom'] ?? '') . ' ' . ($u['pui_nom'] ?? '')) ?: $u['uti_email_normalise']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Société</label><select class="form-select" name="societe_id"><option value="0">Toutes</option><?php foreach (($refs['societes'] ?? []) as $s): ?><option value="<?= (int)$s['soc_id'] ?>" <?= (int)($filters['societe_id'] ?? 0)===(int)$s['soc_id']?'selected':'' ?>><?= $h($s['soc_nom']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Action</label><input class="form-control" name="action" value="<?= $h($filters['action'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Début</label><input type="date" class="form-control" name="date_debut" value="<?= $h($filters['date_debut'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Fin</label><input type="date" class="form-control" name="date_fin" value="<?= $h($filters['date_fin'] ?? '') ?>"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filtrer</button></div></div></form>
  <div class="card"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Date</th><th>Utilisateur</th><th>Action</th><th>Société</th><th>Concession</th><th>Marque</th><th>Service</th><th>Équipe</th><th>IP</th></tr></thead><tbody>
    <?php foreach ($contextes as $c): ?><tr><td><?= $h($c['hcu_cree_le']) ?></td><td><?= $h(trim(($c['pui_prenom'] ?? '') . ' ' . ($c['pui_nom'] ?? '')) ?: $c['uti_email_normalise']) ?></td><td><span class="badge bg-secondary"><?= $h($c['hcu_action']) ?></span></td><td><?= $h($c['societe_nom'] ?? '—') ?></td><td><?= $h($c['concession_nom'] ?? '—') ?></td><td><?= $h($c['marque_nom'] ?? '—') ?></td><td><?= $h($c['service_nom'] ?? '—') ?></td><td><?= $h($c['equipe_nom'] ?? '—') ?></td><td><?= $h($c['hcu_adresse_ip'] ?? '') ?></td></tr><?php endforeach; ?>
    <?php if (!$contextes): ?><tr><td colspan="9" class="text-center text-muted py-4">Aucun historique.</td></tr><?php endif; ?>
  </tbody></table></div></div>
</div>
