<?php $h = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); ?>
<div class="container-fluid py-3">
  <div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Affectations d’étiquettes</h1><a class="btn btn-outline-secondary" href="<?= url('/labels') ?>">Étiquettes</a></div>
  <form method="post" action="<?= url('/label-assignments/attach') ?>" class="card card-body mb-3">
    <?= $csrfField ?? csrf_field() ?>
    <div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">Étiquette</label><select class="form-select" name="etiquette_id" required><?php foreach (($refs['etiquettes'] ?? []) as $e): ?><option value="<?= (int)$e['eti_id'] ?>"><?= $h($e['eti_libelle']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Cible type</label><input class="form-control" name="cible_type" value="general" required></div><div class="col-md-2"><label class="form-label">Cible ID</label><input class="form-control" type="number" min="0" name="cible_id" value="0" required></div><div class="col-md-3"><button class="btn btn-primary w-100">Affecter</button></div></div>
  </form>
  <div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ID</th><th>Étiquette</th><th>Cible</th><th>Société étiquette</th><th>Créée</th><th></th></tr></thead><tbody><?php foreach ($affectations as $a): ?><tr><td><?= (int)$a['afe_id'] ?></td><td><?= $h($a['eti_libelle']) ?> <code><?= $h($a['eti_code']) ?></code></td><td><code><?= $h($a['afe_cible_type']) ?>#<?= (int)$a['afe_cible_id'] ?></code></td><td><?= $h($a['etiquette_societe_nom'] ?? 'Globale') ?></td><td><?= $h($a['afe_cree_le'] ?? '') ?></td><td class="text-end"><form method="post" action="<?= url('/label-assignments/' . (int)$a['afe_id'] . '/detach') ?>" data-confirm="Retirer cette affectation ?"><?= $csrfField ?? csrf_field() ?><button class="btn btn-sm btn-outline-danger">Retirer</button></form></td></tr><?php endforeach; ?><?php if (!$affectations): ?><tr><td colspan="6" class="text-center text-muted py-4">Aucune affectation.</td></tr><?php endif; ?></tbody></table></div></div>
</div>
