<?php
declare(strict_types=1);
$e = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$items = $items ?? [];
$csrf = $csrf_token ?? '';
$isSuperAdmin = !empty($isSuperAdmin);
$activeCompanyId = (int) ($companyId ?? $activeCompanyId ?? 0);
$publicationScopes = $publicationScopes ?? ['interne' => 'Interne société'];
$decodePre = static function (?string $json): string {
    if (!$json) return '—';
    $decoded = json_decode($json, true);
    if (!is_array($decoded) || $decoded === []) return '—';
    return implode(', ', array_slice(array_map('strval', $decoded), 0, 3));
};
$scopeBadge = static function (string $scope): string {
    return match ($scope) {
        'plateforme' => '<span class="badge badge-dark">Plateforme</span>',
        'reseau' => '<span class="badge badge-info">Réseau</span>',
        default => '<span class="badge badge-secondary">Interne</span>',
    };
};
?>
<section class="content-header"><div class="container-fluid"><div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-certificate mr-2"></i>Certifications</h1></div><div class="col-sm-6 text-right"><?php if (!empty($publicationScopes)): ?><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#modal-qualification-add"><i class="fas fa-plus mr-1"></i>Nouvelle certification</button><?php endif; ?></div></div></div></section>
<section class="content"><div class="container-fluid"><div class="alert alert-light border small">Le module historique <strong>Qualifications</strong> reste compatible, mais les créations et modifications sont réservées aux profils <strong>PDG</strong> et <strong>chef de service</strong>.</div><div class="card"><div class="card-header"><h3 class="card-title"><?= count($items) ?> certification(s)</h3></div><div class="card-body p-0"><table class="table table-striped table-hover table-sm mb-0"><thead class="thead-light"><tr><th>Code</th><th>Nom</th><th>Prérequis</th><th>Portée</th><th>Statut</th><th class="text-right" style="width:110px">Actions</th></tr></thead><tbody><?php foreach ($items as $item): ?><?php $isActive = !empty($item['qua_is_active']); $ownerId = (int) ($item['cer_societe_proprietaire_id'] ?? $item['qua_owner_company_id'] ?? 0); $scope = (string) ($item['cer_portee_code'] ?? $item['qua_scope_code'] ?? $item['qua_scope'] ?? ($ownerId > 0 ? 'interne' : 'plateforme')); $canEdit = $isSuperAdmin || ($ownerId > 0 && $ownerId === $activeCompanyId); ?><tr class="<?= $isActive ? '' : 'text-muted' ?>"><td><code><?= $e($item['qua_code'] ?? '') ?></code></td><td><strong><?= $e($item['qua_name'] ?? '') ?></strong><br><small><?= $e($item['qua_description'] ?? '') ?></small></td><td><small><?= $e($decodePre($item['cer_prerequis_json'] ?? null)) ?></small></td><td><?= $scopeBadge($scope) ?><?php if (!empty($item['qua_company_name'])): ?><small class="text-muted ml-1"><?= $e($item['qua_company_name']) ?></small><?php endif; ?></td><td><?= $isActive ? '<span class="badge badge-success">Active</span>' : '<span class="badge badge-secondary">Inactive</span>' ?></td><td class="text-right text-nowrap"><?php if ($canEdit): ?><a class="btn btn-xs btn-outline-secondary" href="/admin/qualifications/<?= (int) $item['qua_id'] ?>/edit" title="Modifier"><i class="fas fa-edit"></i></a><form method="post" action="/admin/qualifications/<?= (int) $item['qua_id'] ?>/toggle" style="display:inline"><input type="hidden" name="_csrf_token" value="<?= $e($csrf) ?>"><button class="btn btn-xs <?= $isActive ? 'btn-outline-danger' : 'btn-outline-success' ?>" title="<?= $isActive ? 'Désactiver' : 'Activer' ?>"><i class="fas fa-<?= $isActive ? 'ban' : 'check' ?>"></i></button></form><?php else: ?><span class="text-muted small">Lecture</span><?php endif; ?></td></tr><?php endforeach; ?><?php if ($items === []): ?><tr><td colspan="6" class="text-center text-muted p-3">Aucune certification.</td></tr><?php endif; ?></tbody></table></div></div></div></section>
<div class="modal fade" id="modal-qualification-add" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header bg-info text-white"><h5 class="modal-title"><i class="fas fa-certificate mr-2"></i>Nouvelle certification</h5><button type="button" class="close text-white" data-dismiss="modal">&times;</button></div><form method="post" action="/admin/qualifications/store"><input type="hidden" name="_csrf_token" value="<?= $e($csrf) ?>"><div class="modal-body"><div class="form-group"><label>Code <span class="text-danger">*</span></label><input class="form-control form-control-sm" name="cer_code" required placeholder="EX: HV_TECH" style="text-transform:uppercase"></div><div class="form-group"><label>Nom <span class="text-danger">*</span></label><input class="form-control form-control-sm" name="cer_nom" required></div><div class="form-group"><label>Description</label><textarea class="form-control form-control-sm" name="cer_description" rows="3"></textarea></div><div class="form-group"><label>Prérequis JSON</label><textarea class="form-control form-control-sm" name="cer_prerequis_json" rows="2" placeholder='["COMPETENCE_X"]'></textarea></div><div class="form-group"><label>Portée de publication</label><select class="form-control form-control-sm" name="cer_portee_code"><?php foreach ($publicationScopes as $code => $label): ?><option value="<?= $e($code) ?>"><?= $e($label) ?></option><?php endforeach; ?></select></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Annuler</button><button class="btn btn-info">Créer</button></div></form></div></div></div>
